# Generated by Django 3.2.6 on 2021-09-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210915_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
