# Generated by Django 3.2.6 on 2021-09-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20210916_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
