# Generated by Django 3.2.6 on 2021-09-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20210916_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
